import { AdditionalInfoProps } from "./additionalInfo";
import { PriceTagsProps } from "./priceTags";

export type ItemProps = {
  uniqueId: string;
  id: string;
  productId: string;
  productRefId?: any;
  refId?: any;
  ean: string;
  name: string;
  skuName: string;
  modalType?: any;
  parentItemIndex?: any;
  parentAssemblyBinding?: any;
  assemblies: any[];
  priceValidUntil: string;
  tax: number;
  price: number;
  priceLabel?: string;
  listPrice: number;
  manualPrice?: any;
  sellingPrice: number;
  sellingPriceLabel?: string;
  rewardValue: number;
  isGift: boolean;
  additionalInfo: AdditionalInfoProps;
  preSaleDate?: any;
  productCategoryIds: string;
  productCategories: { [x: string]: string };
  quantity: number;
  seller: string;
  sellerChain: string[];
  imageUrl: string;
  detailUrl: string;
  components: any[];
  bundleItems: any[];
  attachments: any[];
  attachmentOfferings: any[];
  offerings: any[];
  priceTags: PriceTagsProps[];
  availability: string;
  measurementUnit: string;
  unitMultiplier: number;
  manufacturerCode?: any;
};
